import jsPDF from 'jspdf';
import { getAgencySettings } from '@/utils/agencySettings';

export interface CVData {
  fullName: string;
  phone: string;
  email?: string;
  address: string;
  tagline?: string;
  dateOfBirth?: string;
  nationality?: string;
  maritalStatus?: string;
  languages: string[];
  educationLevel: string;
  educationSchool?: string;
  educationYear?: string;
  experienceYears: number;
  expectedSalary: number;
  skills: string[];
  careerObjective?: string;
  professionalSummary?: string;
  workExperiences?: { position: string; company: string; duration: string; responsibilities: string }[];
  declaration?: string;
  references?: string;
  enhancedSkills?: string[];
}

export type TemplateId = 'professional' | 'modern' | 'minimal';

export const TEMPLATES = [
  { id: 'professional' as const, name: 'Professional', description: 'Classic layout with borders and sections', color: 'hsl(217, 91%, 60%)' },
  { id: 'modern' as const, name: 'Modern', description: 'Bold header with accent colors', color: 'hsl(142, 76%, 36%)' },
  { id: 'minimal' as const, name: 'Minimal', description: 'Clean and simple design', color: 'hsl(222, 47%, 11%)' },
];

function addWatermark(doc: jsPDF) {
  const settings = getAgencySettings();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  if (settings.logoBase64 || settings.logoUrl) {
    const logoData = settings.logoBase64 || settings.logoUrl;
    if (logoData) {
      try {
        const logoSize = 80;
        doc.saveGraphicsState();
        doc.setGState(doc.GState({ opacity: 0.08 }));
        doc.addImage(logoData, 'PNG', (pageWidth - logoSize) / 2, (pageHeight - logoSize) / 2, logoSize, logoSize);
        doc.restoreGraphicsState();
      } catch (e) { /* ignore */ }
    }
  }
}

function addFooter(doc: jsPDF) {
  const settings = getAgencySettings();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 12;
  doc.setLineWidth(0.3);
  doc.setDrawColor(150, 150, 150);
  doc.line(20, footerY - 5, pageWidth - 20, footerY - 5);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by ${settings.agencyName}`, 20, footerY);
  doc.text(new Date().toLocaleDateString('en-NP', { year: 'numeric', month: 'long', day: 'numeric' }), pageWidth - 20 - 35, footerY);
}

// ─────────────────────────────────────────────
// PROFESSIONAL TEMPLATE — A4 single-page modern layout
// Matches the "Sachina Chhetri" reference design
// ─────────────────────────────────────────────
function renderProfessionalCV(data: CVData, scale: number): { doc: jsPDF; finalY: number; pageH: number; bottomLimit: number } {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();   // 210
  const pageH = doc.internal.pageSize.getHeight();  // 297
  const M = 14; // outer margin
  const contentW = pageW - M * 2;
  const bottomLimit = pageH - 12; // reserve space for footer brand

  // Color tokens
  const ink: [number, number, number] = [17, 24, 39];
  const body: [number, number, number] = [55, 65, 81];
  const muted: [number, number, number] = [107, 114, 128];
  const label: [number, number, number] = [120, 126, 138];
  const cardBorder: [number, number, number] = [226, 232, 240];
  const chipBg: [number, number, number] = [248, 250, 252];
  const chipBorder: [number, number, number] = [226, 232, 240];

  // Scale helpers — fonts and vertical spacing shrink together
  const fs = (n: number) => n * scale;
  const sp = (n: number) => n * scale;
  // Line heights derived from font size (mm ≈ pt * 0.353)
  const lh = (fontPt: number) => fontPt * scale * 0.42;

  let y = sp(18);

  // Top tint strip
  doc.setFillColor(245, 247, 252);
  doc.rect(0, 0, pageW, 6, 'F');

  // Name
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...ink);
  doc.setFontSize(fs(30));
  doc.text(data.fullName, M, y + sp(6));
  y += sp(12);

  // Tagline
  const tagline = data.tagline
    || (data.skills && data.skills.length > 0 ? data.skills.slice(0, 3).join('  •  ') : 'Professional');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fs(11));
  doc.setTextColor(...body);
  doc.text(tagline, M, y + sp(4));
  y += sp(10);

  // Contact pills
  const chips: string[] = [];
  if (data.address) chips.push(data.address);
  if (data.phone) chips.push(data.phone);
  if (data.email) chips.push(data.email);
  doc.setFontSize(fs(9));
  let chipX = M;
  const chipY = y + sp(2);
  const chipH = sp(6.5);
  chips.forEach((text) => {
    const tw = doc.getTextWidth(text);
    const w = tw + sp(6);
    doc.setDrawColor(...chipBorder);
    doc.setFillColor(...chipBg);
    doc.setLineWidth(0.3);
    doc.roundedRect(chipX, chipY, w, chipH, 3.2, 3.2, 'FD');
    doc.setTextColor(...body);
    doc.text(text, chipX + sp(3), chipY + sp(4.4));
    chipX += w + sp(3);
  });
  y += sp(14);

  const sectionLabel = (title: string) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(fs(8.5));
    doc.setTextColor(...label);
    const spaced = title.toUpperCase().split('').join(' ');
    doc.text(spaced, M, y);
    y += sp(5);
  };

  const wrappedText = (text: string, x: number, width: number, lineHmm: number, sizePt: number) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(fs(sizePt));
    doc.setTextColor(...body);
    const lines = doc.splitTextToSize(text, width);
    doc.text(lines, x, y);
    y += lines.length * lineHmm;
  };

  // Professional Summary
  const summary = data.professionalSummary
    || data.careerObjective
    || `Dedicated professional with ${data.experienceYears} year${data.experienceYears !== 1 ? 's' : ''} of practical experience. Skilled in ${(data.skills || []).slice(0, 4).join(', ') || 'multiple areas'}. Reliable, adaptable, and committed to delivering quality work.`;
  sectionLabel('Professional Summary');
  wrappedText(summary, M, contentW, lh(9.5), 9.5);
  y += sp(5);

  // Professional Experience
  const exps = data.workExperiences && data.workExperiences.length > 0 ? data.workExperiences : [];
  if (exps.length > 0) {
    sectionLabel('Professional Experience');

    const primaryCompany = exps[0].company;
    const primaryMeta = [data.address, `${data.experienceYears} Year${data.experienceYears !== 1 ? 's' : ''}`, exps[0].duration]
      .filter(Boolean).join('  •  ');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(fs(13));
    doc.setTextColor(...ink);
    doc.text(primaryCompany, M, y);
    y += sp(4.5);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(fs(9));
    doc.setTextColor(...muted);
    doc.text(primaryMeta, M, y);
    y += sp(5);

    const colGap = sp(5);
    const colW = (contentW - colGap) / 2;
    const cardPadX = sp(4);
    const cardPadY = sp(4);
    const bulletLH = lh(9);

    doc.setFontSize(fs(9));
    const cardData = exps.map((work) => {
      const bullets = (work.responsibilities || '')
        .split(/\n|(?<=\.) /).map((s) => s.trim()).filter(Boolean).slice(0, 3);
      const allLines = bullets.flatMap((b) => doc.splitTextToSize('• ' + b, colW - cardPadX * 2 - sp(2)));
      return { work, bullets, allLines };
    });

    for (let i = 0; i < cardData.length; i += 2) {
      const left = cardData[i];
      const right = cardData[i + 1];
      const leftLines = left.allLines.length;
      const rightLines = right ? right.allLines.length : 0;
      const cardH = Math.max(leftLines, rightLines) * bulletLH + cardPadY * 2 + sp(7);

      [{ d: left, x: M }, right ? { d: right, x: M + colW + colGap } : null].forEach((entry) => {
        if (!entry) return;
        doc.setDrawColor(...cardBorder);
        doc.setFillColor(255, 255, 255);
        doc.setLineWidth(0.3);
        doc.roundedRect(entry.x, y, colW, cardH, 2.2, 2.2, 'S');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(fs(10.5));
        doc.setTextColor(...ink);
        doc.text(entry.d.work.position, entry.x + cardPadX, y + cardPadY + sp(3));

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(fs(9));
        doc.setTextColor(...body);
        let by = y + cardPadY + sp(8);
        entry.d.bullets.forEach((b) => {
          const lines = doc.splitTextToSize('•  ' + b, colW - cardPadX * 2 - sp(2));
          doc.text(lines, entry.x + cardPadX, by);
          by += lines.length * bulletLH;
        });
      });
      y += cardH + sp(4);
    }
    y += sp(2);
  }

  // Education & Languages
  if (data.educationLevel || data.languages.length > 0) {
    sectionLabel('Education & Languages');
    const colGap = sp(5);
    const colW = (contentW - colGap) / 2;
    const padX = sp(4);
    const padY = sp(4.5);

    const eduMain = data.educationLevel || 'Not specified';
    const eduSchool = data.educationSchool || '';
    const eduYear = data.educationYear || '';
    const langs = data.languages.length > 0 ? data.languages : ['Nepali'];

    const rowH = lh(9.5);
    const eduLines = 1 + (eduSchool ? 1 : 0) + (eduYear ? 1 : 0);
    const langLines = langs.length;
    const cardH = Math.max(eduLines, langLines) * rowH + padY * 2 + sp(7);

    doc.setDrawColor(...cardBorder);
    doc.setLineWidth(0.3);
    doc.roundedRect(M, y, colW, cardH, 2.2, 2.2, 'S');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(fs(10.5));
    doc.setTextColor(...ink);
    doc.text('Education', M + padX, y + padY + sp(3));
    let ey = y + padY + sp(8.5);
    doc.setFontSize(fs(9.5));
    doc.text(eduMain, M + padX, ey); ey += rowH;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(fs(9));
    doc.setTextColor(...body);
    if (eduSchool) { doc.text(eduSchool, M + padX, ey); ey += rowH; }
    if (eduYear) { doc.text(eduYear, M + padX, ey); }

    const lx = M + colW + colGap;
    doc.setDrawColor(...cardBorder);
    doc.roundedRect(lx, y, colW, cardH, 2.2, 2.2, 'S');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(fs(10.5));
    doc.setTextColor(...ink);
    doc.text('Languages', lx + padX, y + padY + sp(3));
    let ly = y + padY + sp(8.5);
    doc.setFontSize(fs(9));
    langs.forEach((lang) => {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...ink);
      doc.text(lang, lx + padX, ly);
      const lw = doc.getTextWidth(lang);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...body);
      doc.text('  —  Professional Working Proficiency', lx + padX + lw, ly);
      ly += rowH;
    });

    y += cardH + sp(6);
  }

  // Skills (chip pills)
  if (data.skills && data.skills.length > 0) {
    sectionLabel('Skills');
    let sx = M;
    const sH = sp(6);
    doc.setFontSize(fs(8.8));
    data.skills.forEach((skill) => {
      const tw = doc.getTextWidth(skill);
      const w = tw + sp(5);
      if (sx + w > pageW - M) { sx = M; y += sH + sp(2); }
      doc.setDrawColor(...chipBorder);
      doc.setFillColor(...chipBg);
      doc.setLineWidth(0.3);
      doc.roundedRect(sx, y, w, sH, 2.5, 2.5, 'FD');
      doc.setTextColor(...body);
      doc.text(skill, sx + sp(2.5), y + sp(4));
      sx += w + sp(2.5);
    });
    y += sH + sp(6);
  }

  // Career Objective (when both summary and objective exist)
  if (data.careerObjective && data.professionalSummary) {
    sectionLabel('Career Objective');
    wrappedText(data.careerObjective, M, contentW, lh(9.5), 9.5);
    y += sp(4);
  }

  // Branding footer
  const settings = getAgencySettings();
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...muted);
  const brand = `Prepared by ${settings.agencyName}`;
  const brandW = doc.getTextWidth(brand);
  doc.text(brand, (pageW - brandW) / 2, pageH - 8);

  return { doc, finalY: y, pageH, bottomLimit };
}

export function generateProfessionalCV(data: CVData): jsPDF {
  // Auto-fit: try scales from 1.0 down to 0.7 in 0.04 steps until content fits one A4 page
  let result = renderProfessionalCV(data, 1);
  if (result.finalY <= result.bottomLimit) return result.doc;

  for (let scale = 0.96; scale >= 0.7; scale -= 0.04) {
    const r = renderProfessionalCV(data, scale);
    if (r.finalY <= r.bottomLimit) return r.doc;
    result = r;
  }
  return result.doc; // fallback to smallest tried
}

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 15;

  addWatermark(doc);

  // Bold header block
  doc.setFillColor(34, 55, 94);
  doc.rect(0, 0, pageWidth, 50, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.text(data.fullName.toUpperCase(), margin, 28);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const contact = [data.phone, data.address].filter(Boolean).join('  •  ');
  doc.text(contact, margin, 40);

  y = 65;

  const addSection = (title: string) => {
    if (y > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      addWatermark(doc);
      y = 25;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(34, 55, 94);
    doc.text(title.toUpperCase(), margin, y);
    y += 2;
    doc.setDrawColor(34, 55, 94);
    doc.setLineWidth(1);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  };

  // Personal Details
  const personal = [];
  if (data.dateOfBirth) personal.push(`DOB: ${data.dateOfBirth}`);
  if (data.nationality) personal.push(data.nationality);
  if (data.maritalStatus) personal.push(data.maritalStatus);
  if (data.languages.length > 0) personal.push(`Languages: ${data.languages.join(', ')}`);

  if (personal.length > 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(personal.join('  |  '), margin, y);
    y += 12;
  }

  if (data.careerObjective) {
    addSection('Objective');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.careerObjective, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 10;
  }

  if (data.professionalSummary) {
    addSection('Profile');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.professionalSummary, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 10;
  }

  if (data.workExperiences && data.workExperiences.length > 0) {
    addSection('Experience');
    data.workExperiences.forEach(work => {
      if (y > doc.internal.pageSize.getHeight() - 60) {
        doc.addPage();
        addWatermark(doc);
        y = 25;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(34, 55, 94);
      doc.text(`${work.position} — ${work.company}`, margin, y);
      y += 5;
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(work.duration, margin, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const lines = doc.splitTextToSize(`• ${work.responsibilities}`, contentWidth - 5);
      doc.text(lines, margin + 5, y);
      y += lines.length * 5 + 8;
    });
  }

  addSection('Education');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`• ${data.educationLevel || 'Not specified'}`, margin, y);
  y += 12;

  addSection('Skills');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  const skillText = data.skills.map(s => `• ${s}`).join('    ');
  const skillLines = doc.splitTextToSize(skillText, contentWidth);
  doc.text(skillLines, margin, y);
  y += skillLines.length * 5 + 12;

  addSection('Expected Salary');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`NPR ${data.expectedSalary.toLocaleString()} per month (negotiable)`, margin, y);
  y += 15;

  // Declaration
  const decl = data.declaration || 'I declare the above is true to the best of my knowledge.';
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  const declLines = doc.splitTextToSize(decl, contentWidth);
  doc.text(declLines, margin, y);
  y += declLines.length * 4 + 15;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text('Date: _______________', margin, y);
  doc.text('Signature: _______________', pageWidth - margin - 60, y);

  addFooter(doc);
  return doc;
}

export function generateMinimalCV(data: CVData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 25;
  const contentWidth = pageWidth - margin * 2;
  let y = 30;

  addWatermark(doc);

  // Name
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(28);
  doc.text(data.fullName, margin, y);
  y += 8;

  // Contact line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  const contact = [data.phone, data.address, data.nationality].filter(Boolean).join('  ·  ');
  doc.text(contact, margin, y);
  y += 5;
  if (data.languages.length > 0) {
    doc.text(data.languages.join(' · '), margin, y);
    y += 5;
  }
  y += 10;

  const addSection = (title: string) => {
    if (y > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      addWatermark(doc);
      y = 30;
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(title.toUpperCase(), margin, y);
    y += 3;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  };

  if (data.careerObjective) {
    addSection('Objective');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.careerObjective, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 8;
  }

  if (data.professionalSummary) {
    addSection('About');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.professionalSummary, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 8;
  }

  if (data.workExperiences && data.workExperiences.length > 0) {
    addSection('Experience');
    data.workExperiences.forEach(work => {
      if (y > doc.internal.pageSize.getHeight() - 60) {
        doc.addPage();
        addWatermark(doc);
        y = 30;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      doc.text(work.position, margin, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(` — ${work.company}, ${work.duration}`, margin + doc.getTextWidth(work.position), y);
      y += 6;
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(work.responsibilities, contentWidth - 5);
      doc.text(lines, margin + 5, y);
      y += lines.length * 5 + 8;
    });
  }

  addSection('Education');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(data.educationLevel || 'Not specified', margin, y);
  y += 10;

  addSection('Skills');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(data.skills.join('  ·  '), margin, y);
  y += 10;

  addSection('Salary Expectation');
  doc.text(`NPR ${data.expectedSalary.toLocaleString()}/month`, margin, y);
  y += 15;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text('Date: _______________', margin, y);
  doc.text('Signature: _______________', pageWidth - margin - 60, y);

  addFooter(doc);
  return doc;
}

export function generateCV(data: CVData, template: TemplateId): jsPDF {
  switch (template) {
    case 'modern': return generateModernCV(data);
    case 'minimal': return generateMinimalCV(data);
    case 'professional':
    default: return generateProfessionalCV(data);
  }
}
