import jsPDF from 'jspdf';
import { getAgencySettings } from '@/utils/agencySettings';

export interface CVData {
  fullName: string;
  phone: string;
  address: string;
  dateOfBirth?: string;
  nationality?: string;
  maritalStatus?: string;
  languages: string[];
  educationLevel: string;
  experienceYears: number;
  expectedSalary: number;
  skills: string[];
  careerObjective?: string;
  professionalSummary?: string;
  workExperiences?: { position: string; company: string; duration: string; responsibilities: string }[];
  declaration?: string;
  references?: string;
  enhancedSkills?: string[];
}

export type TemplateId = 'professional' | 'modern' | 'minimal';

export const TEMPLATES = [
  { id: 'professional' as const, name: 'Professional', description: 'Classic layout with borders and sections', color: 'hsl(217, 91%, 60%)' },
  { id: 'modern' as const, name: 'Modern', description: 'Bold header with accent colors', color: 'hsl(142, 76%, 36%)' },
  { id: 'minimal' as const, name: 'Minimal', description: 'Clean and simple design', color: 'hsl(222, 47%, 11%)' },
];

function addWatermark(doc: jsPDF) {
  const settings = getAgencySettings();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  if (settings.logoBase64 || settings.logoUrl) {
    const logoData = settings.logoBase64 || settings.logoUrl;
    if (logoData) {
      try {
        const logoSize = 80;
        doc.saveGraphicsState();
        doc.setGState(doc.GState({ opacity: 0.08 }));
        doc.addImage(logoData, 'PNG', (pageWidth - logoSize) / 2, (pageHeight - logoSize) / 2, logoSize, logoSize);
        doc.restoreGraphicsState();
      } catch (e) { /* ignore */ }
    }
  }
}

function addFooter(doc: jsPDF) {
  const settings = getAgencySettings();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 12;
  doc.setLineWidth(0.3);
  doc.setDrawColor(150, 150, 150);
  doc.line(20, footerY - 5, pageWidth - 20, footerY - 5);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by ${settings.agencyName}`, 20, footerY);
  doc.text(new Date().toLocaleDateString('en-NP', { year: 'numeric', month: 'long', day: 'numeric' }), pageWidth - 20 - 35, footerY);
}

export function generateProfessionalCV(data: CVData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  addWatermark(doc);

  // Header line
  doc.setDrawColor(40, 40, 40);
  doc.setLineWidth(1.5);
  doc.line(margin, 15, pageWidth - margin, 15);

  // Name
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(24);
  const nameWidth = doc.getTextWidth(data.fullName.toUpperCase());
  doc.text(data.fullName.toUpperCase(), (pageWidth - nameWidth) / 2, y);
  y += 10;

  // Contact
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  const contact = [data.phone, data.address].filter(Boolean).join('  |  ');
  const contactW = doc.getTextWidth(contact);
  doc.text(contact, (pageWidth - contactW) / 2, y);
  y += 8;

  // Personal
  const personal = [];
  if (data.dateOfBirth) {
    const age = new Date().getFullYear() - new Date(data.dateOfBirth).getFullYear();
    personal.push(`Age: ${age}`);
  }
  if (data.nationality) personal.push(data.nationality);
  if (data.maritalStatus) personal.push(data.maritalStatus);
  if (personal.length > 0) {
    const personalLine = personal.join('  |  ');
    doc.setFontSize(9);
    const pw = doc.getTextWidth(personalLine);
    doc.text(personalLine, (pageWidth - pw) / 2, y);
    y += 6;
  }

  if (data.languages.length > 0) {
    const langLine = `Languages: ${data.languages.join(', ')}`;
    doc.setFontSize(9);
    const lw = doc.getTextWidth(langLine);
    doc.text(langLine, (pageWidth - lw) / 2, y);
    y += 8;
  }

  y += 5;
  doc.setLineWidth(0.5);
  doc.setDrawColor(100, 100, 100);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;

  const addSection = (title: string) => {
    if (y > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      addWatermark(doc);
      y = 25;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text(title.toUpperCase(), margin, y);
    y += 2;
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + 35, y);
    y += 8;
  };

  // Career Objective
  if (data.careerObjective) {
    addSection('Career Objective');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.careerObjective, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 10;
  }

  // Professional Summary
  if (data.professionalSummary) {
    addSection('Professional Summary');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.professionalSummary, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 12;
  }

  // Work Experience
  if (data.workExperiences && data.workExperiences.length > 0) {
    addSection('Work Experience');
    data.workExperiences.forEach(work => {
      if (y > doc.internal.pageSize.getHeight() - 60) {
        doc.addPage();
        addWatermark(doc);
        y = 25;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      doc.text(work.position, margin + 5, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(80, 80, 80);
      doc.text(`| ${work.company}`, margin + 5 + doc.getTextWidth(work.position + ' '), y);
      y += 5;
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(work.duration, margin + 5, y);
      y += 5;
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const respLines = doc.splitTextToSize(`• ${work.responsibilities}`, contentWidth - 10);
      doc.text(respLines, margin + 5, y);
      y += respLines.length * 5 + 8;
    });
  }

  // Education
  addSection('Education');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`• ${data.educationLevel || 'Not specified'}`, margin + 5, y);
  y += 12;

  // Skills
  addSection('Skills & Competencies');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  const skillsPerRow = 3;
  const skillWidth = contentWidth / skillsPerRow;
  data.skills.forEach((skill, index) => {
    const col = index % skillsPerRow;
    const row = Math.floor(index / skillsPerRow);
    if (col === 0 && row > 0) y += 6;
    doc.text(`• ${skill}`, margin + 5 + col * skillWidth, y);
  });
  y += 12;

  // Expected Salary
  addSection('Expected Remuneration');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`NPR ${data.expectedSalary.toLocaleString()} per month (negotiable)`, margin + 5, y);
  y += 12;

  // References
  if (data.references) {
    addSection('References');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    doc.text(`• ${data.references}`, margin + 5, y);
    y += 12;
  }

  // Declaration
  const decl = data.declaration || 'I hereby declare that all the information provided above is true and correct to the best of my knowledge and belief.';
  addSection('Declaration');
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  const declLines = doc.splitTextToSize(decl, contentWidth);
  doc.text(declLines, margin, y);
  y += declLines.length * 4 + 15;

  // Signature
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text('Date: _______________', margin, y);
  doc.text('Signature: _______________', pageWidth - margin - 60, y);

  addFooter(doc);
  return doc;
}

export function generateModernCV(data: CVData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 15;

  addWatermark(doc);

  // Bold header block
  doc.setFillColor(34, 55, 94);
  doc.rect(0, 0, pageWidth, 50, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.text(data.fullName.toUpperCase(), margin, 28);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const contact = [data.phone, data.address].filter(Boolean).join('  •  ');
  doc.text(contact, margin, 40);

  y = 65;

  const addSection = (title: string) => {
    if (y > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      addWatermark(doc);
      y = 25;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(34, 55, 94);
    doc.text(title.toUpperCase(), margin, y);
    y += 2;
    doc.setDrawColor(34, 55, 94);
    doc.setLineWidth(1);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  };

  // Personal Details
  const personal = [];
  if (data.dateOfBirth) personal.push(`DOB: ${data.dateOfBirth}`);
  if (data.nationality) personal.push(data.nationality);
  if (data.maritalStatus) personal.push(data.maritalStatus);
  if (data.languages.length > 0) personal.push(`Languages: ${data.languages.join(', ')}`);

  if (personal.length > 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(personal.join('  |  '), margin, y);
    y += 12;
  }

  if (data.careerObjective) {
    addSection('Objective');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.careerObjective, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 10;
  }

  if (data.professionalSummary) {
    addSection('Profile');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.professionalSummary, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 10;
  }

  if (data.workExperiences && data.workExperiences.length > 0) {
    addSection('Experience');
    data.workExperiences.forEach(work => {
      if (y > doc.internal.pageSize.getHeight() - 60) {
        doc.addPage();
        addWatermark(doc);
        y = 25;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(34, 55, 94);
      doc.text(`${work.position} — ${work.company}`, margin, y);
      y += 5;
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(work.duration, margin, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const lines = doc.splitTextToSize(`• ${work.responsibilities}`, contentWidth - 5);
      doc.text(lines, margin + 5, y);
      y += lines.length * 5 + 8;
    });
  }

  addSection('Education');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`• ${data.educationLevel || 'Not specified'}`, margin, y);
  y += 12;

  addSection('Skills');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  const skillText = data.skills.map(s => `• ${s}`).join('    ');
  const skillLines = doc.splitTextToSize(skillText, contentWidth);
  doc.text(skillLines, margin, y);
  y += skillLines.length * 5 + 12;

  addSection('Expected Salary');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`NPR ${data.expectedSalary.toLocaleString()} per month (negotiable)`, margin, y);
  y += 15;

  // Declaration
  const decl = data.declaration || 'I declare the above is true to the best of my knowledge.';
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  const declLines = doc.splitTextToSize(decl, contentWidth);
  doc.text(declLines, margin, y);
  y += declLines.length * 4 + 15;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text('Date: _______________', margin, y);
  doc.text('Signature: _______________', pageWidth - margin - 60, y);

  addFooter(doc);
  return doc;
}

export function generateMinimalCV(data: CVData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 25;
  const contentWidth = pageWidth - margin * 2;
  let y = 30;

  addWatermark(doc);

  // Name
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(28);
  doc.text(data.fullName, margin, y);
  y += 8;

  // Contact line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  const contact = [data.phone, data.address, data.nationality].filter(Boolean).join('  ·  ');
  doc.text(contact, margin, y);
  y += 5;
  if (data.languages.length > 0) {
    doc.text(data.languages.join(' · '), margin, y);
    y += 5;
  }
  y += 10;

  const addSection = (title: string) => {
    if (y > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      addWatermark(doc);
      y = 30;
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(title.toUpperCase(), margin, y);
    y += 3;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  };

  if (data.careerObjective) {
    addSection('Objective');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.careerObjective, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 8;
  }

  if (data.professionalSummary) {
    addSection('About');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(data.professionalSummary, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 8;
  }

  if (data.workExperiences && data.workExperiences.length > 0) {
    addSection('Experience');
    data.workExperiences.forEach(work => {
      if (y > doc.internal.pageSize.getHeight() - 60) {
        doc.addPage();
        addWatermark(doc);
        y = 30;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      doc.text(work.position, margin, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(` — ${work.company}, ${work.duration}`, margin + doc.getTextWidth(work.position), y);
      y += 6;
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(work.responsibilities, contentWidth - 5);
      doc.text(lines, margin + 5, y);
      y += lines.length * 5 + 8;
    });
  }

  addSection('Education');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(data.educationLevel || 'Not specified', margin, y);
  y += 10;

  addSection('Skills');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(data.skills.join('  ·  '), margin, y);
  y += 10;

  addSection('Salary Expectation');
  doc.text(`NPR ${data.expectedSalary.toLocaleString()}/month`, margin, y);
  y += 15;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text('Date: _______________', margin, y);
  doc.text('Signature: _______________', pageWidth - margin - 60, y);

  addFooter(doc);
  return doc;
}

export function generateCV(data: CVData, template: TemplateId): jsPDF {
  switch (template) {
    case 'modern': return generateModernCV(data);
    case 'minimal': return generateMinimalCV(data);
    case 'professional':
    default: return generateProfessionalCV(data);
  }
}
